name: "ZAP Baseline Scan"

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_SHORT_SHA: ${{ github.sha }}
      CI_COMMIT_SHA: ${{ github.sha }}
      CI_COMMIT_REF_NAME: ${{ github.ref }}
      CI_PROJECT_URL: ${{ github.repository_url }}
      DEFECTDOJO_HOST: ${{ secrets.DEFECTDOJO_HOST }}
      DEFECTDOJO_USER: ${{ secrets.DEFECTDOJO_USER }}
      DEFECTDOJO_PASSWORD: ${{ secrets.DEFECTDOJO_PASSWORD }}
      VERSION: "1.0.0"
      CI_PIPELINE_ID: ${{ github.run_id }}
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Checkout the code
        uses: actions/checkout@v2


      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
#      - name: run auditjs
#        run: |
#          npx auditjs@latest iq > audit-report.json
#      - name: Upload audit report
#        uses: actions/upload-artifact@v2
#        with:
#          name: audit-report
#          path: audit-report.json

      - name: Run ZAP Scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:weekly zap-baseline.py \
          -t https://preview.owasp-juice.shop -g gen.conf -x zap-report.xml
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://preview.owasp-juice.shop'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-x report_xml'

      - name: Upload XML report to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zap-report-xml
          path: .zap/report_xml.xml


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pip
        run: |
          python -m ensurepip

      - name: install requests
        run: |
          pip install requests
      - name: DefectDojo Settings
        run: |
          python scripts/defectdojo_settings.py
      - name: DefectDojo Scan
        run: |
          python scripts/send_scans.py