name: "ZAP Baseline Scan"

on:
  push:
    branches:
      - master


jobs:
  zap_scan:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_SHORT_SHA: ${{ github.sha }}
      CI_COMMIT_SHA: ${{ github.sha }}
      CI_COMMIT_REF_NAME: ${{ github.ref }}
      CI_PROJECT_URL: ${{ github.repository_url }}
      DEFECTDOJO_HOST: ${{ secrets.DEFECTDOJO_HOST }}
      DEFECTDOJO_USER: ${{ secrets.DEFECTDOJO_USER }}
      DEFECTDOJO_PASSWORD: ${{ secrets.DEFECTDOJO_PASSWORD }}
      VERSION: "1.0.0"
      CI_PIPELINE_ID: ${{ github.run_id }}
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Set up OWASP ZAP
        run: |
            mkdir $HOME/zap
            cd $HOME/zap
            curl -sL https://raw.githubusercontent.com/zaproxy/zaproxy/main/docker/Dockerfile > Dockerfile
            docker build -t owasp/zap2docker-stable:latest .

      - name: OWASP ZAP Scan
        run: |
                mkdir $HOME/zap/wrk
                docker run --rm -v $HOME/zap:/zap owasp/zap2docker-stable:latest zap-api-scan.py -t http://webapi:8000/v3/api-docs -f openapi -x /zap/wrk/owasp-zap-scan-report.xml || true
                cp $HOME/zap/wrk/owasp-zap-scan-report.xml $GITHUB_WORKSPACE

      - name: Upload OWASP ZAP Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: owasp-zap-scan-report
          path: owasp-zap-scan-report.xml
#      - name: ZAP Scan
#        run: |
#          - mkdir /zap/wrk/
#          - /zap/zap-api-scan.py -t https://preview.owasp-juice.shop -f openapi -x owasp-zap-scan-report.xml || true
#          - cp /zap/wrk/owasp-zap-scan-report.xml
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          docker_name: 'owasp/zap2docker-stable:latest'
#          target: 'https://preview.owasp-juice.shop'
#          rules_file_name: '.zap/rules.tsv'
#          cmd_options: '-a'
#
#      - name: Upload Gitleaks JSON report to artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: zap-report
#          path: owasp-zap-scan-report.xml

      - name: Download and extract artifact
        uses: actions/download-artifact@v2
        with:
          name: zap-report
          path: .github/workflows/
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pip
        run: |
          python -m ensurepip

      - name: install requests
        run: |
          pip install requests
      - name: DefectDojo Settings
        run: |
          python scripts/defectdojo_settings.py
      - name: DefectDojo Scan
        run: |
          python scripts/send_scans.py