name: "ZAP Baseline Scan"

on:
  push:
    branches:
      - master


jobs:
  zap_scan:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_SHORT_SHA: ${{ github.sha }}
      CI_COMMIT_SHA: ${{ github.sha }}
      CI_COMMIT_REF_NAME: ${{ github.ref }}
      CI_PROJECT_URL: ${{ github.repository_url }}
      DEFECTDOJO_HOST: ${{ secrets.DEFECTDOJO_HOST }}
      DEFECTDOJO_USER: ${{ secrets.DEFECTDOJO_USER }}
      DEFECTDOJO_PASSWORD: ${{ secrets.DEFECTDOJO_PASSWORD }}
      VERSION: "1.0.0"
      CI_PIPELINE_ID: ${{ github.run_id }}
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://preview.owasp-juice.shop'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -o /zap/report.json'  # Add command option to output JSON report
      - name: Upload Gitleaks JSON report to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: report.json

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pip
        run: |
          python -m ensurepip

      - name: install requests
        run: |
          pip install requests
      - name: DefectDojo Settings
        run: |
          python scripts/defectdojo_settings.py
      - name: DefectDojo Scan
        run: |
          python scripts/send_scans.py